### ISSUE TITLE
This container version is no longer available from the Crunchy Data Developer Program

### ISSUE THREAD

**Issue by piratetm** [BigKAA/youtube#62]
Невозможно выполнить (с впн и без него): kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.2/installers/kubectl/postgres-operator.yml
Кубик пишет, что не может скачать имейдж.

Залез в конфиг, попробовал пойти по ссылке того самого имейджа registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos8-4.7.5 выдает ошибку:
{ "errors":[{"code":"404","message":"This container version is no longer available from the Crunchy Data Developer Program. For information on accessing these containers, please contact info@crunchydata.com." }]}

**Comment by BigKAA** [comment]
Сорри, но материалы жестко прикреплены к конкретному видео.
Если в каком то приложении что то со временем перестаёт работать, изменения вноситься не будут.
