### ISSUE TITLE
Предложение по корректировке README.md

### ISSUE THREAD

**Issue by SterhLight** [BigKAA/youtube#84]
Приветствую.
У вас README оформлен по концепции ссылок на отдельные страницы. А на этих страницах отсутствуют ссылки, по которым можно вернуться обратно или на стартовую страницу. Можно конечно использовать в браузере кнопку возврата, но это не кашерно))) Это просто предложение. Предлагаю реализовать.

**Comment by BigKAA** [comment]
На всех страницах есть вот такая ссылка.

![image](https://github.com/BigKAA/youtube/assets/60059562/96ccf228-be21-4125-93e2-9baf856ade01)

**Comment by SterhLight** [comment]
Как она мне поможет попасть на страницу, с которой я пришел? Да никак) Я с редми по kubeadm перехожу на страницу, например, "почему не kubesprey", а обратно через эту ссылочку, и ручками/глазками опять в папку kubeadm, и потом в редми. А было бы удобно в конце страницы сразу иметь ссылку туда.
В любом случае, это просто предложение, от благодарного подписчика)))
